version: '2'
networks:
  neohabitat:
    external: false

services:
  neohabitatmariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=qlink
      - MYSQL_USER=qlink
      - MYSQL_PASSWORD=qlink
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - neohabitat
  neohabitatmongo:
    image: mongo:4.0
    command: "--smallfiles"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - neohabitat
  pushserver:
    build:
      context: ./pushserver
      dockerfile: ./pushserver.Dockerfile
    environment:
      - NEOHABITAT_BRIDGE_ELKO_HOST=neohabitat:2018
      - NEOHABITAT_MONGO_HOST=neohabitatmongo:27017
      - NEOHABITAT_SERVER_PORT=1337
      - NEOHABITAT_SHOULD_ENABLE_DEBUGGER=true
      - HABIPROXY_ELKO_HOST=neohabitat
      - HABIPROXY_ELKO_PORT=9000
      - PUSH_SERVER_CONFIG=./config.dev.yml
      - PUSH_SERVER_MONGO_URL=mongodb://neohabitatmongo
      - NODE_ENV=development
      - HABIPROXY_LISTEN_HOST=127.0.0.1
      - HABIPROXY_LISTEN_PORT=2018
    ports:
      - "1987:1987"
      - "9000:9000"
      - "80:1701"
    networks:
      - neohabitat
    depends_on:
      - neohabitatmongo
  neohabitat:
    build: .
    # make sure to build this with `docker compose build` when doing development to compile your local changes.
    image: frandallfarmer/neohabitat
    privileged: true
    environment:
      - NEOHABITAT_BRIDGE_ELKO_HOST=neohabitat:2018
      - NEOHABITAT_MONGO_HOST=neohabitatmongo:27017
      - NEOHABITAT_SHOULD_ENABLE_DEBUGGER=true
      - NEOHABITAT_SHOULD_RUN_BRIDGE=true
      - NEOHABITAT_SHOULD_RUN_NEOHABITAT=true
      - NEOHABITAT_SHOULD_UPDATE_SCHEMA=true
      - NEOHABITAT_SERVER_HOST=neohabitat
      - NEOHABITAT_SERVER_PORT=1337
      - HABIPROXY_ELKO_HOST=neohabitat
      - HABIPROXY_ELKO_PORT=9000
      - NODE_ENV=development
      - PUSH_SERVER_CONFIG=./config.dev.yml
      - PUSH_SERVER_MONGO_URL=mongodb://neohabitatmongo
    ports:
      - "2018:2018"
      - "1337:1337"
    depends_on:
      - neohabitatmongo
      - pushserver
    networks:
      - neohabitat
  qlink:
    image: philcollins/qlink
#    build: ../qlink/
    environment:
      - QLINK_DB_HOST=neohabitatmariadb
      - QLINK_DB_JDBC_URI=jdbc:mysql://neohabitatmariadb:3306/qlink
      - QLINK_DB_USERNAME=qlink
      - QLINK_DB_PASSWORD=qlink
      - QLINK_HABITAT_HOST=neohabitat
      - QLINK_HABITAT_PORT=1337
      - QLINK_HABITAT_USE_FRAMING=true
    ports:
      - "1986:1986"
    depends_on:
      - neohabitat
      - pushserver
      - neohabitatmariadb
    networks:
      - neohabitat
    ulimits:
      nofile:
        soft: 10000
        hard: 10000
  # bots:
  #   build:
  #     context: ./habibots
  #   environment:
  #     - HABIBOTS_HOST=neohabitat
  #     - HABIBOTS_PORT=1337
  #   depends_on:
  #     - qlink
  #   networks:
  #     - neohabitat
  #   entrypoint: ['/habibots/run']
  #   command: ['hatchery', 'eliza']
