---
viceJsUrl: https://sgeo.github.io/experimental/neohabitat-joystick/x64.js

websocketProxy:
  clientAddr: habitat.themade.org:1987
  listenAddr: 0.0.0.0:1987
  remoteAddr: habitat.themade.org:1986

backgroundImages:
  - https://raw.githubusercontent.com/frandallfarmer/neohabitat-doc/master/docs/images/neohabitat_splash.png
  - https://raw.githubusercontent.com/frandallfarmer/neohabitat-doc/master/docs/images/launcher_login.png
  - https://raw.githubusercontent.com/frandallfarmer/neohabitat-doc/master/docs/images/habitat_imagery.png
  - https://raw.githubusercontent.com/frandallfarmer/neohabitat-doc/master/docs/images/neohabitat_downtown.png

cookieSessionKeys:
  - "E0<<LBlxUN.f,fFS?+9@27L:shHk2@18q5[qH{EFIKMd[+<>V2OzuJ&au%TZX:!"

externalPages:
  unknown: /region/unknown
